import "./globals.css";
import Navbar from "@/app/components/Navbar";
import IntlProvider from "@/app/providers/IntlProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
  const locale = params?.locale || "en"; // Get locale dynamically

  return (
    <html lang={locale}>
      <body className="font-geist antialiased">
        <IntlProvider locale={locale}>
          <Navbar />
          {children}
        </IntlProvider>
      </body>
    </html>
  );
}
